name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    # don't run on pushes to forks
    if: github.event_name == 'pull_request' || github.repository == 'harvard-lil/wacz-signing'

    steps:
      - uses: actions/checkout@v2

      ### prepare to install trusted self-signed SSL certs

      - name: Install mkcert
        # from https://computingforgeeks.com/create-locally-trusted-ssl-certificates-on-linux-macos-using-mkcert/
        run: |
          sudo apt-get update
          sudo apt install wget libnss3-tools
          curl -s https://api.github.com/repos/FiloSottile/mkcert/releases/latest | grep browser_download_url  | grep linux-amd64 | cut -d '"' -f 4 | wget -qi -
          mv mkcert-v*-linux-amd64 mkcert
          chmod a+x mkcert
          sudo mv mkcert /usr/local/bin/
          mkcert -install

      ### run tests ###

      - name: pytest
        run: |
          set -x
          poetry install
          bash ./set-up-dot-env.sh
          poetry run pytest
